In [12]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [28]:
# 제휴사A
df_A = pd.read_csv('./dataset/제휴사A로그.csv',encoding='cp949')
df_A=df_A.drop('Unnamed: 0',axis=1)
df_A=df_A.fillna(0)

In [42]:
df_a=df_A.copy()
df_a.head()

고객번호    A_총구매액1    A_총구매액2    A_총구매액3    A_총구매액4    A_총구매액5    A_총구매액6  \
0     1  16.009884  16.204441  16.309872  16.814168  16.024814  16.010687   
1     2  16.445114  16.167517  16.634964  15.646239  16.738430  16.093625   
2     3   0.000000  11.319438   0.000000   0.000000   0.000000   0.000000   
3     4  14.019726  15.063572  14.718498  14.119375  14.311811  14.321407   
4     6  13.870047  14.559063  14.618875  14.358465  14.700459  14.676558   

     A_총구매액7    A_총구매액8   A_구매횟수1   A_구매횟수2   A_구매횟수3   A_구매횟수4   A_구매횟수5  \
0  15.974682  15.255446  4.795791  4.709530  4.867534  4.983607  4.934474   
1  16.558953  16.109647  5.214936  5.049856  4.941642  4.836282  4.948760   
2   0.000000   0.000000  0.000000  0.693147  0.000000  0.000000  0.000000   
3  14.374280  13.816504  4.406719  4.795791  4.094345  3.850148  4.605170   
4  14.519033  14.343223  3.637586  3.951244  3.806662  3.912023  3.931826   

    A_구매횟수6   A_구매횟수7   A_구매횟수8  
0  4.663439  4.204693  4.127134  
1  4.595120  4.804021  4.787492  
2  0.000000  0.000000  0.000000  
3  4.488636  4.382027  4.356709  
4  3.761200  3.583519  3.988984

In [43]:
def cat_sales(x):

    if x <= bins[1]:
        return 1
    elif( x > bins[1]) and (x <= bins[2]) :
        return 2
    elif( x > bins[2]) and (x <=bins[3]) :
        return 3    
    elif( x > bins[3]) and (x <=bins[4]) :
        return 4
    elif( x > bins[4]) :
        return 5    
#     elif( x > bins[4]) and (x <=bins[5]) :
#         return 5    
#     elif( x > bins[5]) and (x <=bins[6]) :
#         return 6    
#     elif( x > bins[6]) and (x <=bins[7]) :
#         return 7    
#     elif( x > bins[7]) and (x <=bins[8]) :
#         return 8    
#     elif( x > bins[8]) and (x <=bins[9]) :
#         return 9  
#     elif( x > bins[9]):
#         return 10    
    
df_col=df_a.columns[1:]

for a in df_col:
    _,bins =np.histogram(df_a[a],bins= 5) 
    print(bins)
    df_a[a]=df_a[a].apply(lambda x : cat_sales(x))   
df_a

[ 0.          3.98239572  7.96479144 11.94718716 15.92958288 19.9119786 ]
[ 0.          3.96546564  7.93093129 11.89639693 15.86186258 19.82732822]
[ 0.          3.91902947  7.83805895 11.75708842 15.6761179  19.59514737]
[ 0.          4.1760293   8.35205861 12.52808791 16.70411721 20.88014651]
[ 0.          3.96411457  7.92822914 11.89234371 15.85645828 19.82057285]
[ 0.          4.07061198  8.14122396 12.21183594 16.28244792 20.3530599 ]
[ 0.          4.07135032  8.14270064 12.21405096 16.28540127 20.35675159]
[ 0.          4.08100239  8.16200479 12.24300718 16.32400957 20.40501197]
[0.         1.15114844 2.30229689 3.45344533 4.60459377 5.75574221]
[0.         1.16870888 2.33741777 3.50612665 4.67483553 5.84354442]
[0.         1.16520002 2.33040004 3.49560006 4.66080009 5.82600011]
[0.         1.15241028 2.30482055 3.45723083 4.60964111 5.76205138]
[0.         1.18485116 2.36970232 3.55455348 4.73940464 5.9242558 ]
[0.         1.24491169 2.48982337 3.73473506 4.97964674 6.22455843]


고객번호  A_총구매액1  A_총구매액2  A_총구매액3  A_총구매액4  A_총구매액5  A_총구매액6  A_총구매액7  \
0          1        5        5        5        5        5        4        4   
1          2        5        5        5        4        5        4        5   
2          3        1        3        1        1        1        1        1   
3          4        4        4        4        4        4        4        4   
4          6        4        4        4        4        4        4        4   
...      ...      ...      ...      ...      ...      ...      ...      ...   
18861  19333        4        4        4        3        4        3        3   
18862  19334        1        1        1        1        1        1        4   
18863  19335        1        1        3        3        3        4        1   
18864  19336        4        4        4        4        4        4        4   
18865  19337        1        1        1        3        3        1        1   

       A_총구매액8  A_구매횟수1  A_구매횟수2  A_구매횟수3  A_구매횟수4  A_구매횟수5  A_구매횟수6  A_구매횟수7  \
0            4        5        5        5        5        5        4        4   
1            4        5        5        5        5        5        4        5   
2            1        1        1        1        1        1        1        1   
3            4        4        5        4        4        4        4        4   
4            4        4        4        4        4        4        4        4   
...        ...      ...      ...      ...      ...      ...      ...      ...   
18861        4        4        4        4        4        4        3        3   
18862        1        1        1        1        1        1        1        2   
18863        1        1        1        1        2        1        2        1   
18864        4        2        4        4        4        4        3        4   
18865        3        1        1        1        1        1        1        1   

       A_구매횟수8  
0            4  
1            5  
2            1  
3            4  
4            4  
...        ...  
18861        4  
18862        1  
18863        1  
18864        4  
18865        1  

[18866 rows x 17 columns]

In [44]:
for i in range(1,8):
    display(df_a.iloc[:,i].value_counts())

4    9441
1    5121
3    2310
5    1971
2      23
Name: A_총구매액1, dtype: int64

4    9174
1    5042
5    2448
3    2179
2      23
Name: A_총구매액2, dtype: int64

4    8811
1    5085
5    2932
3    2025
2      13
Name: A_총구매액3, dtype: int64

4    10392
1     4404
3     3374
5      639
2       57
Name: A_총구매액4, dtype: int64

4    9557
1    4591
5    2389
3    2314
2      15
Name: A_총구매액5, dtype: int64

4    9956
1    4604
3    2786
5    1496
2      24
Name: A_총구매액6, dtype: int64

4    9960
1    4764
3    2814
5    1298
2      30
Name: A_총구매액7, dtype: int64

In [45]:
# 제휴사A
df_B = pd.read_csv('./dataset/제휴사B로그.csv',encoding='cp949')
df_B=df_B.drop('Unnamed: 0',axis=1)
df_B=df_B.fillna(0)

In [46]:
df_b=df_B.copy()
df_b.head()

고객번호    B_총구매액1    B_총구매액2    B_총구매액3    B_총구매액4    B_총구매액5    B_총구매액6  \
0     1   9.973620   0.000000   8.577535  12.705052  12.164162   9.895405   
1     2  10.309453   0.000000   0.000000  10.626048  11.470842  10.607278   
2     3   0.000000   0.000000   8.970051   0.000000   0.000000   0.000000   
3     4   0.000000  11.320178  12.404624  12.109898  11.220847  12.538401   
4     6  13.777983  13.809803  14.108818  13.604158  13.846169  13.312243   

     B_총구매액7    B_총구매액8   B_구매횟수1   B_구매횟수2   B_구매횟수3   B_구매횟수4   B_구매횟수5  \
0  11.740666  11.012825  0.693147  0.000000  1.386294  3.663562  2.484907   
1   0.000000   0.000000  0.693147  0.000000  0.000000  2.079442  1.791759   
2   0.000000   0.000000  0.000000  0.000000  1.098612  0.000000  0.000000   
3  13.177775  12.387281  0.000000  2.772589  3.091042  3.091042  2.484907   
4  14.478877  13.766454  5.010635  4.912655  4.905275  4.882802  5.123964   

    B_구매횟수6   B_구매횟수7   B_구매횟수8  
0  0.693147  1.945910  1.609438  
1  1.386294  0.000000  0.000000  
2  0.000000  0.000000  0.000000  
3  3.258097  3.218876  2.302585  
4  4.779123  5.267858  5.117994

In [47]:
df_col=df_b.columns[1:]

for a in df_col:
    _,bins =np.histogram(df_b[a],bins= 5) 
    print(bins)
    df_b[a]=df_b[a].apply(lambda x : cat_sales(x))   
df_b

[ 0.          4.02172733  8.04345467 12.065182   16.08690934 20.10863667]
[ 0.          4.11458569  8.22917138 12.34375707 16.45834275 20.57292844]
[ 0.          4.07028563  8.14057126 12.2108569  16.28114253 20.35142816]
[ 0.          3.66497294  7.32994588 10.99491882 14.65989176 18.3248647 ]
[ 0.          3.76997966  7.53995932 11.30993898 15.07991864 18.8498983 ]
[ 0.          3.51564665  7.0312933  10.54693995 14.06258661 17.57823326]
[ 0.          3.73235018  7.46470035 11.19705053 14.92940071 18.66175088]
[ 0.          3.53554335  7.07108669 10.60663004 14.14217339 17.67771674]
[0.         1.48873274 2.97746547 4.46619821 5.95493095 7.44366368]
[0.         1.33692235 2.67384469 4.01076704 5.34768938 6.68461173]
[0.         1.31389628 2.62779257 3.94168885 5.25558514 6.56948142]
[0.         1.38034744 2.76069488 4.14104232 5.52138977 6.90173721]
[0.         1.34904727 2.69809454 4.04714181 5.39618908 6.74523635]
[0.         1.39149947 2.78299895 4.17449842 5.5659979  6.95749737]


고객번호  B_총구매액1  B_총구매액2  B_총구매액3  B_총구매액4  B_총구매액5  B_총구매액6  B_총구매액7  \
0          1        3        1        3        4        4        3        4   
1          2        3        1        1        3        4        4        1   
2          3        1        1        3        1        1        1        1   
3          4        1        3        4        4        3        4        4   
4          6        4        4        4        4        4        4        4   
...      ...      ...      ...      ...      ...      ...      ...      ...   
18861  19333        4        4        3        4        4        4        3   
18862  19334        4        4        4        5        4        4        3   
18863  19335        4        4        4        4        4        5        4   
18864  19336        1        1        1        1        1        1        3   
18865  19337        1        1        3        1        3        1        1   

       B_총구매액8  B_구매횟수1  B_구매횟수2  B_구매횟수3  B_구매횟수4  B_구매횟수5  B_구매횟수6  B_구매횟수7  \
0            4        1        1        2        3        2        1        2   
1            1        1        1        1        2        2        1        1   
2            1        1        1        1        1        1        1        1   
3            4        1        3        3        3        2        3        3   
4            4        4        4        4        4        4        4        4   
...        ...      ...      ...      ...      ...      ...      ...      ...   
18861        3        3        4        3        4        3        2        1   
18862        4        4        5        5        5        4        4        1   
18863        5        3        5        5        4        4        4        4   
18864        1        1        1        1        1        1        1        1   
18865        4        1        1        2        1        2        1        1   

       B_구매횟수8  
0            2  
1            1  
2            1  
3            2  
4            4  
...        ...  
18861        3  
18862        3  
18863        4  
18864        1  
18865        1  

[18866 rows x 17 columns]

In [48]:
for i in range(1,8):
    display(df_b.iloc[:,i].value_counts())

4    10035
1     5219
3     3552
2       32
5       28
Name: B_총구매액1, dtype: int64

4    9538
1    5328
3    3922
2      56
5      22
Name: B_총구매액2, dtype: int64

4    10449
1     4806
3     3543
2       41
5       27
Name: B_총구매액3, dtype: int64

4    11671
1     4685
3     1893
5      604
2       13
Name: B_총구매액4, dtype: int64

4    11756
1     4634
3     2233
5      232
2       11
Name: B_총구매액5, dtype: int64

4    8258
5    4747
1    4718
3    1140
2       3
Name: B_총구매액6, dtype: int64

4    11799
1     4494
3     1903
5      662
2        8
Name: B_총구매액7, dtype: int64

In [51]:
df_s1=df_a[['고객번호', 'A_총구매액1', 'A_총구매액2', 'A_총구매액3', 'A_총구매액4', 'A_총구매액5','A_총구매액6', 'A_총구매액7']]
df_s2=df_b[['고객번호', 'B_총구매액1', 'B_총구매액2', 'B_총구매액3', 'B_총구매액4', 'B_총구매액5','B_총구매액6', 'B_총구매액7']]

In [53]:
df_s2

고객번호  B_총구매액1  B_총구매액2  B_총구매액3  B_총구매액4  B_총구매액5  B_총구매액6  B_총구매액7
0          1        3        1        3        4        4        3        4
1          2        3        1        1        3        4        4        1
2          3        1        1        3        1        1        1        1
3          4        1        3        4        4        3        4        4
4          6        4        4        4        4        4        4        4
...      ...      ...      ...      ...      ...      ...      ...      ...
18861  19333        4        4        3        4        4        4        3
18862  19334        4        4        4        5        4        4        3
18863  19335        4        4        4        4        4        5        4
18864  19336        1        1        1        1        1        1        3
18865  19337        1        1        3        1        3        1        1

[18866 rows x 8 columns]

In [54]:
df_s = pd.merge(df_s1,df_s2, on='고객번호')
df_s

고객번호  A_총구매액1  A_총구매액2  A_총구매액3  A_총구매액4  A_총구매액5  A_총구매액6  A_총구매액7  \
0          1        5        5        5        5        5        4        4   
1          2        5        5        5        4        5        4        5   
2          3        1        3        1        1        1        1        1   
3          4        4        4        4        4        4        4        4   
4          6        4        4        4        4        4        4        4   
...      ...      ...      ...      ...      ...      ...      ...      ...   
18861  19333        4        4        4        3        4        3        3   
18862  19334        1        1        1        1        1        1        4   
18863  19335        1        1        3        3        3        4        1   
18864  19336        4        4        4        4        4        4        4   
18865  19337        1        1        1        3        3        1        1   

       B_총구매액1  B_총구매액2  B_총구매액3  B_총구매액4  B_총구매액5  B_총구매액6  B_총구매액7  
0            3        1        3        4        4        3        4  
1            3        1        1        3        4        4        1  
2            1        1        3        1        1        1        1  
3            1        3        4        4        3        4        4  
4            4        4        4        4        4        4        4  
...        ...      ...      ...      ...      ...      ...      ...  
18861        4        4        3        4        4        4        3  
18862        4        4        4        5        4        4        3  
18863        4        4        4        4        4        5        4  
18864        1        1        1        1        1        1        3  
18865        1        1        3        1        3        1        1  

[18866 rows x 15 columns]

In [55]:
df_s.to_csv('./dataset/로그등급화.csv',encoding='cp949')

In [56]:
#변동계수 구하기
df_A = pd.read_csv('./dataset/제휴사A로그.csv',encoding='cp949')
df_A=df_A.drop('Unnamed: 0',axis=1)
df_A=df_A.fillna(0)

In [64]:
df_cv_a = df_A[['고객번호', 'A_총구매액1', 'A_총구매액2', 'A_총구매액3', 'A_총구매액4', 'A_총구매액5','A_총구매액6', 'A_총구매액7']]

m = df_cv_a.iloc[1,1:].mean()
s = df_cv_a.iloc[1,1:].std()
cv = (df_cv_a.iloc[1,1:].std())/(df_cv_a.iloc[1,1:].mean())
print(cv)

0.02339309475900252


In [66]:
df_cv_a.loc[1,'고객번호']

2

In [68]:
for i in df_cv_a.index:
    m=df_cv_a.iloc[i,1:].mean()
    if m == 0:
        cv=0
    elif m != 0:
        cv = (df_cv_a.iloc[i,1:].std())/m
    df_cv_a.loc[i,'CV'] = cv
df_cv_a

고객번호    A_총구매액1    A_총구매액2    A_총구매액3    A_총구매액4    A_총구매액5  \
0          1  16.009884  16.204441  16.309872  16.814168  16.024814   
1          2  16.445114  16.167517  16.634964  15.646239  16.738430   
2          3   0.000000  11.319438   0.000000   0.000000   0.000000   
3          4  14.019726  15.063572  14.718498  14.119375  14.311811   
4          6  13.870047  14.559063  14.618875  14.358465  14.700459   
...      ...        ...        ...        ...        ...        ...   
18861  19333  12.957411  13.363524  13.034729  12.289743  12.660994   
18862  19334   0.000000   0.000000   0.000000   0.000000   0.000000   
18863  19335   0.000000   0.000000  11.721158  11.583468  11.160399   
18864  19336  13.000044  15.038158  15.088248  15.468059  14.886883   
18865  19337   0.000000   0.000000   0.000000  12.259936  11.164700   

         A_총구매액6    A_총구매액7        CV  
0      16.010687  15.974682  0.404009  
1      16.093625  16.558953  0.404158  
2       0.000000   0.000000  2.278603  
3      14.321407  14.374280  0.404125  
4      14.676558  14.519033  0.403976  
...          ...        ...       ...  
18861  12.183530  12.151046  0.037416  
18862   0.000000  12.972052  2.645751  
18863  13.808043   0.000000  0.943261  
18864  15.173278  15.774721  0.060108  
18865   0.000000   0.000000  1.710437  

[18866 rows x 9 columns]

In [69]:
df_cv_a[df_cv_a['CV']==0]

고객번호  A_총구매액1  A_총구매액2  A_총구매액3  A_총구매액4  A_총구매액5  A_총구매액6  A_총구매액7  \
232      236      0.0      0.0      0.0      0.0      0.0      0.0      0.0   
279      284      0.0      0.0      0.0      0.0      0.0      0.0      0.0   
337      342      0.0      0.0      0.0      0.0      0.0      0.0      0.0   
481      487      0.0      0.0      0.0      0.0      0.0      0.0      0.0   
506      512      0.0      0.0      0.0      0.0      0.0      0.0      0.0   
...      ...      ...      ...      ...      ...      ...      ...      ...   
18681  19106      0.0      0.0      0.0      0.0      0.0      0.0      0.0   
18731  19161      0.0      0.0      0.0      0.0      0.0      0.0      0.0   
18741  19173      0.0      0.0      0.0      0.0      0.0      0.0      0.0   
18793  19254      0.0      0.0      0.0      0.0      0.0      0.0      0.0   
18839  19308      0.0      0.0      0.0      0.0      0.0      0.0      0.0   

        CV  
232    0.0  
279    0.0  
337    0.0  
481    0.0  
506    0.0  
...    ...  
18681  0.0  
18731  0.0  
18741  0.0  
18793  0.0  
18839  0.0  

[527 rows x 9 columns]

In [89]:
df_log = pd.read_csv('./dataset/로그등급화_수정.csv', encoding='cp949')
df_log = df_log.drop(['Unnamed: 0','Unnamed: 16','A변동계수','B변동계수'],axis=1)
df_log

고객번호  A_총구매액1  A_총구매액2  A_총구매액3  A_총구매액4  A_총구매액5  A_총구매액6  A_총구매액7  \
0          1        5        5        5        5        5        4        4   
1          2        5        5        5        4        5        4        5   
2          3        1        3        1        1        1        1        1   
3          4        4        4        4        4        4        4        4   
4          6        4        4        4        4        4        4        4   
...      ...      ...      ...      ...      ...      ...      ...      ...   
18861  19333        4        4        4        3        4        3        3   
18862  19334        1        1        1        1        1        1        4   
18863  19335        1        1        3        3        3        4        1   
18864  19336        4        4        4        4        4        4        4   
18865  19337        1        1        1        3        3        1        1   

       B_총구매액1  B_총구매액2  ...  B_총구매액4  B_총구매액5  B_총구매액6  B_총구매액7  A증감율  A변동율  \
0            3        1  ...        4        4        3        4    -1     1   
1            3        1  ...        3        4        4        1     0     4   
2            1        1  ...        1        1        1        1     0     4   
3            1        3  ...        4        3        4        4     0     0   
4            4        4  ...        4        4        4        4     0     0   
...        ...      ...  ...      ...      ...      ...      ...   ...   ...   
18861        4        4  ...        4        4        4        3    -1     3   
18862        4        4  ...        5        4        4        3     3     3   
18863        4        4  ...        4        4        5        4     0     6   
18864        1        1  ...        1        1        1        3     0     0   
18865        1        1  ...        1        3        1        1     0     4   

       B증감율  B변동율  A증감(0.8)*변동(0.2)  B증감(0.8)*변동(0.2)  
0         1     7              -0.6               2.2  
1        -2     8               0.8               0.0  
2         0     4               0.8               0.8  
3         3     5               0.0               3.4  
4         0     0               0.0               0.0  
...     ...   ...               ...               ...  
18861    -1     3              -0.2              -0.2  
18862    -1     3               3.0              -0.2  
18863     0     2               1.2               0.4  
18864     2     2               0.0               2.0  
18865     0     8               0.8               1.6  

[18866 rows x 21 columns]

In [90]:
df_cv_a[['고객번호','CV']]

고객번호        CV
0          1  0.404009
1          2  0.404158
2          3  2.278603
3          4  0.404125
4          6  0.403976
...      ...       ...
18861  19333  0.037416
18862  19334  2.645751
18863  19335  0.943261
18864  19336  0.060108
18865  19337  1.710437

[18866 rows x 2 columns]

In [91]:
l =df_cv_a[['고객번호','CV']]
l.columns=['고객번호','A_CV']
df_log = pd.merge(df_log,l,how='left',on='고객번호')
df_log

고객번호  A_총구매액1  A_총구매액2  A_총구매액3  A_총구매액4  A_총구매액5  A_총구매액6  A_총구매액7  \
0          1        5        5        5        5        5        4        4   
1          2        5        5        5        4        5        4        5   
2          3        1        3        1        1        1        1        1   
3          4        4        4        4        4        4        4        4   
4          6        4        4        4        4        4        4        4   
...      ...      ...      ...      ...      ...      ...      ...      ...   
18861  19333        4        4        4        3        4        3        3   
18862  19334        1        1        1        1        1        1        4   
18863  19335        1        1        3        3        3        4        1   
18864  19336        4        4        4        4        4        4        4   
18865  19337        1        1        1        3        3        1        1   

       B_총구매액1  B_총구매액2  ...  B_총구매액5  B_총구매액6  B_총구매액7  A증감율  A변동율  B증감율  \
0            3        1  ...        4        3        4    -1     1     1   
1            3        1  ...        4        4        1     0     4    -2   
2            1        1  ...        1        1        1     0     4     0   
3            1        3  ...        3        4        4     0     0     3   
4            4        4  ...        4        4        4     0     0     0   
...        ...      ...  ...      ...      ...      ...   ...   ...   ...   
18861        4        4  ...        4        4        3    -1     3    -1   
18862        4        4  ...        4        4        3     3     3    -1   
18863        4        4  ...        4        5        4     0     6     0   
18864        1        1  ...        1        1        3     0     0     2   
18865        1        1  ...        3        1        1     0     4     0   

       B변동율  A증감(0.8)*변동(0.2)  B증감(0.8)*변동(0.2)      A_CV  
0         7              -0.6               2.2  0.404009  
1         8               0.8               0.0  0.404158  
2         4               0.8               0.8  2.278603  
3         5               0.0               3.4  0.404125  
4         0               0.0               0.0  0.403976  
...     ...               ...               ...       ...  
18861     3              -0.2              -0.2  0.037416  
18862     3               3.0              -0.2  2.645751  
18863     2               1.2               0.4  0.943261  
18864     2               0.0               2.0  0.060108  
18865     8               0.8               1.6  1.710437  

[18866 rows x 22 columns]

In [76]:
#변동계수 구하기
df_B = pd.read_csv('./dataset/제휴사B로그.csv',encoding='cp949')
df_B=df_B.drop('Unnamed: 0',axis=1)
df_B=df_B.fillna(0)
df_cv_b = df_B[['고객번호', 'B_총구매액1', 'B_총구매액2', 'B_총구매액3', 'B_총구매액4', 'B_총구매액5','B_총구매액6', 'B_총구매액7']]

for i in df_cv_b.index:
    m=df_cv_b.iloc[i,1:].mean()
    if m == 0:
        cv=0
    elif m != 0:
        cv = (df_cv_b.iloc[i,1:].std())/m
    df_cv_b.loc[i,'CV'] = cv
df_cv_b

C:\Users\ns2ju\anaconda3\envs\cakd5\lib\site-packages\pandas\core\indexing.py:1684: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.obj[key] = infer_fill_value(value)
C:\Users\ns2ju\anaconda3\envs\cakd5\lib\site-packages\pandas\core\indexing.py:1817: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_column(loc, value, pi)


고객번호    B_총구매액1    B_총구매액2    B_총구매액3    B_총구매액4    B_총구매액5  \
0          1   9.973620   0.000000   8.577535  12.705052  12.164162   
1          2  10.309453   0.000000   0.000000  10.626048  11.470842   
2          3   0.000000   0.000000   8.970051   0.000000   0.000000   
3          4   0.000000  11.320178  12.404624  12.109898  11.220847   
4          6  13.777983  13.809803  14.108818  13.604158  13.846169   
...      ...        ...        ...        ...        ...        ...   
18861  19333  12.097278  12.628470  12.181893  12.135967  11.393613   
18862  19334  13.617968  14.782330  14.847290  14.697767  14.292027   
18863  19335  13.685009  14.781324  14.674818  14.218582  14.415190   
18864  19336   0.000000   0.000000   0.000000   0.000000   0.000000   
18865  19337   0.000000   0.000000   9.364948   0.000000  11.062850   

         B_총구매액6    B_총구매액7        CV  
0       9.895405  11.740666  0.468137  
1      10.607278   0.000000  0.937181  
2       0.000000   0.000000  2.645751  
3      12.538401  13.177775  0.445867  
4      13.312243  14.478877  0.026677  
...          ...        ...       ...  
18861  10.995092   9.511555  0.091328  
18862  13.415882  10.300046  0.117180  
18863  14.416893  14.140179  0.025504  
18864   0.000000  10.183654  2.645751  
18865   0.000000   0.000000  1.716064  

[18866 rows x 9 columns]

In [93]:
df_cv_b[df_cv_b['CV']==0]

고객번호  B_총구매액1  B_총구매액2  B_총구매액3  B_총구매액4  B_총구매액5  B_총구매액6  B_총구매액7  \
20        22      0.0      0.0      0.0      0.0      0.0      0.0      0.0   
37        39      0.0      0.0      0.0      0.0      0.0      0.0      0.0   
83        85      0.0      0.0      0.0      0.0      0.0      0.0      0.0   
91        93      0.0      0.0      0.0      0.0      0.0      0.0      0.0   
113      115      0.0      0.0      0.0      0.0      0.0      0.0      0.0   
...      ...      ...      ...      ...      ...      ...      ...      ...   
18835  19304      0.0      0.0      0.0      0.0      0.0      0.0      0.0   
18845  19314      0.0      0.0      0.0      0.0      0.0      0.0      0.0   
18846  19315      0.0      0.0      0.0      0.0      0.0      0.0      0.0   
18850  19319      0.0      0.0      0.0      0.0      0.0      0.0      0.0   
18853  19324      0.0      0.0      0.0      0.0      0.0      0.0      0.0   

        CV  
20     0.0  
37     0.0  
83     0.0  
91     0.0  
113    0.0  
...    ...  
18835  0.0  
18845  0.0  
18846  0.0  
18850  0.0  
18853  0.0  

[950 rows x 9 columns]

In [94]:
l =df_cv_b[['고객번호','CV']]
l.columns = ['고객번호','B_CV']
df_log = pd.merge(df_log,l,how='left',on='고객번호')
df_log

고객번호  A_총구매액1  A_총구매액2  A_총구매액3  A_총구매액4  A_총구매액5  A_총구매액6  A_총구매액7  \
0          1        5        5        5        5        5        4        4   
1          2        5        5        5        4        5        4        5   
2          3        1        3        1        1        1        1        1   
3          4        4        4        4        4        4        4        4   
4          6        4        4        4        4        4        4        4   
...      ...      ...      ...      ...      ...      ...      ...      ...   
18861  19333        4        4        4        3        4        3        3   
18862  19334        1        1        1        1        1        1        4   
18863  19335        1        1        3        3        3        4        1   
18864  19336        4        4        4        4        4        4        4   
18865  19337        1        1        1        3        3        1        1   

       B_총구매액1  B_총구매액2  ...  B_총구매액6  B_총구매액7  A증감율  A변동율  B증감율  B변동율  \
0            3        1  ...        3        4    -1     1     1     7   
1            3        1  ...        4        1     0     4    -2     8   
2            1        1  ...        1        1     0     4     0     4   
3            1        3  ...        4        4     0     0     3     5   
4            4        4  ...        4        4     0     0     0     0   
...        ...      ...  ...      ...      ...   ...   ...   ...   ...   
18861        4        4  ...        4        3    -1     3    -1     3   
18862        4        4  ...        4        3     3     3    -1     3   
18863        4        4  ...        5        4     0     6     0     2   
18864        1        1  ...        1        3     0     0     2     2   
18865        1        1  ...        1        1     0     4     0     8   

       A증감(0.8)*변동(0.2)  B증감(0.8)*변동(0.2)      A_CV      B_CV  
0                  -0.6               2.2  0.404009  0.468137  
1                   0.8               0.0  0.404158  0.937181  
2                   0.8               0.8  2.278603  2.645751  
3                   0.0               3.4  0.404125  0.445867  
4                   0.0               0.0  0.403976  0.026677  
...                 ...               ...       ...       ...  
18861              -0.2              -0.2  0.037416  0.091328  
18862               3.0              -0.2  2.645751  0.117180  
18863               1.2               0.4  0.943261  0.025504  
18864               0.0               2.0  0.060108  2.645751  
18865               0.8               1.6  1.710437  1.716064  

[18866 rows x 23 columns]

In [85]:
df_log.columns=['고객번호', 'A_총구매액1', 'A_총구매액2', 'A_총구매액3', 'A_총구매액4', 'A_총구매액5','A_총구매액6', 'A_총구매액7', 'B_총구매액1', 'B_총구매액2', 'B_총구매액3', 'B_총구매액4','B_총구매액5', 'B_총구매액6', 'B_총구매액7', 'A증감율', 'A변동율', 'CV', 'B증감율', 'B변동율', 'B_CV',
'A증감(0.8)*변동(0.2)', 'B증감(0.8)*변동(0.2)']
df_log.columns=['고객번호', 'A_총구매액1', 'A_총구매액2', 'A_총구매액3', 'A_총구매액4', 'A_총구매액5','A_총구매액6', 'A_총구매액7', 'B_총구매액1', 'B_총구매액2', 'B_총구매액3', 'B_총구매액4','B_총구매액5', 'B_총구매액6', 'B_총구매액7', 'A증감율', 'A변동율', 'A_CV', 'B증감율', 'B변동율', 'B_CV',
'A증감(0.8)*변동(0.2)', 'B증감(0.8)*변동(0.2)']
df_log

고객번호  A_총구매액1  A_총구매액2  A_총구매액3  A_총구매액4  A_총구매액5  A_총구매액6  A_총구매액7  \
0          1        5        5        5        5        5        4        4   
1          2        5        5        5        4        5        4        5   
2          3        1        3        1        1        1        1        1   
3          4        4        4        4        4        4        4        4   
4          6        4        4        4        4        4        4        4   
...      ...      ...      ...      ...      ...      ...      ...      ...   
18861  19333        4        4        4        3        4        3        3   
18862  19334        1        1        1        1        1        1        4   
18863  19335        1        1        3        3        3        4        1   
18864  19336        4        4        4        4        4        4        4   
18865  19337        1        1        1        3        3        1        1   

       B_총구매액1  B_총구매액2  ...  B_총구매액6  B_총구매액7  A증감율  A변동율  A_CV  B증감율  B변동율  \
0            3        1  ...        3        4    -1     1     1     7  -0.6   
1            3        1  ...        4        1     0     4    -2     8   0.8   
2            1        1  ...        1        1     0     4     0     4   0.8   
3            1        3  ...        4        4     0     0     3     5   0.0   
4            4        4  ...        4        4     0     0     0     0   0.0   
...        ...      ...  ...      ...      ...   ...   ...   ...   ...   ...   
18861        4        4  ...        4        3    -1     3    -1     3  -0.2   
18862        4        4  ...        4        3     3     3    -1     3   3.0   
18863        4        4  ...        5        4     0     6     0     2   1.2   
18864        1        1  ...        1        3     0     0     2     2   0.0   
18865        1        1  ...        1        1     0     4     0     8   0.8   

       B_CV  A증감(0.8)*변동(0.2)  B증감(0.8)*변동(0.2)  
0       2.2          0.404009          0.468137  
1       0.0          0.404158          0.937181  
2       0.8          2.278603          2.645751  
3       3.4          0.404125          0.445867  
4       0.0          0.403976          0.026677  
...     ...               ...               ...  
18861  -0.2          0.037416          0.091328  
18862  -0.2          2.645751          0.117180  
18863   0.4          0.943261          0.025504  
18864   2.0          0.060108          2.645751  
18865   1.6          1.710437          1.716064  

[18866 rows x 23 columns]

In [95]:
df_log.to_csv('./dataset/증감변동cv_제휴사.csv',encoding='cp949')

In [96]:
data_set_con=df_log[['고객번호', 'A증감율','A변동율','A증감(0.8)*변동(0.2)','A_CV','B증감율', 'B변동율', 'B증감(0.8)*변동(0.2)', 'B_CV']]
data_set_con

고객번호  A증감율  A변동율  A증감(0.8)*변동(0.2)      A_CV  B증감율  B변동율  \
0          1    -1     1              -0.6  0.404009     1     7   
1          2     0     4               0.8  0.404158    -2     8   
2          3     0     4               0.8  2.278603     0     4   
3          4     0     0               0.0  0.404125     3     5   
4          6     0     0               0.0  0.403976     0     0   
...      ...   ...   ...               ...       ...   ...   ...   
18861  19333    -1     3              -0.2  0.037416    -1     3   
18862  19334     3     3               3.0  2.645751    -1     3   
18863  19335     0     6               1.2  0.943261     0     2   
18864  19336     0     0               0.0  0.060108     2     2   
18865  19337     0     4               0.8  1.710437     0     8   

       B증감(0.8)*변동(0.2)      B_CV  
0                   2.2  0.468137  
1                   0.0  0.937181  
2                   0.8  2.645751  
3                   3.4  0.445867  
4                   0.0  0.026677  
...                 ...       ...  
18861              -0.2  0.091328  
18862              -0.2  0.117180  
18863               0.4  0.025504  
18864               2.0  2.645751  
18865               1.6  1.716064  

[18866 rows x 9 columns]

In [97]:
data_set_con.to_csv('./dataset/제휴사라벨링.csv',encoding='cp949')

In [83]:
['고객번호', 'A_총구매액1', 'A_총구매액2', 'A_총구매액3', 'A_총구매액4', 'A_총구매액5','A_총구매액6', 'A_총구매액7', 'B_총구매액1', 'B_총구매액2', 'B_총구매액3', 'B_총구매액4','B_총구매액5', 'B_총구매액6', 'B_총구매액7', 'A증감율', 'A변동율', 'CV', 'B증감율', 'B변동율', 'B_CV',
'A증감(0.8)*변동(0.2)', 'B증감(0.8)*변동(0.2)']

['고객번호',
 'A_총구매액1',
 'A_총구매액2',
 'A_총구매액3',
 'A_총구매액4',
 'A_총구매액5',
 'A_총구매액6',
 'A_총구매액7',
 'B_총구매액1',
 'B_총구매액2',
 'B_총구매액3',
 'B_총구매액4',
 'B_총구매액5',
 'B_총구매액6',
 'B_총구매액7',
 'A증감율',
 'A변동율',
 'CV',
 'B증감율',
 'B변동율',
 'B_CV',
 'A증감(0.8)*변동(0.2)',
 'B증감(0.8)*변동(0.2)']